version: '3.9'

networks:
  kong-net:
    external: false

services:
  kong-database:
    image: postgres:13
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    networks:
      - kong-net
    ports:
      - "5432:5432"
    volumes:
      - ./kong-data:/var/lib/postgresql/data
  
  zipkin:
    image: openzipkin/zipkin:2
    networks:
      - kong-net
    ports:
      - "9411:9411"
    restart: on-failure

  kong-gateway:
    image: kong/kong-gateway:3.6.1.1
    depends_on:
      - kong-database
    # command: ["kong", "migrations", "bootstrap"]
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
      # KONG_LICENSE_DATA: # license data here
    networks:
      - kong-net
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002" 

volumes:
  kong-data: 
