version: "3.9"

networks:
  app-network:
    driver: bridge

volumes:
  db-data:

services:
  db:
    # image: mysql:8.0.32 
    image: belemon81/internship:projects-app-mysql
    ports:
      - "3307:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bookstore
    networks:
      - app-network
    volumes:
      - ./db-data:/var/lib/mysql 

  app-backend:
    image: belemon81/internship:projects-app-backend
    # build: ./BookStore_BE
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/bookstore
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - app-network
    depends_on:
      - db

  app-frontend:
    image: belemon81/internship:projects-app-frontend
    # build: ./ProjectEx
    ports:
      - "4200:4200"
    networks:
      - app-network
    depends_on:
      - app-backend
