version: "3.9"

networks:
  app-network:
    driver: bridge

volumes:
  db-data:

services:
  db:
    image: mysql:8.0.32  
    ports:
      - "3307:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bookstore
    networks:
      - app-network
    volumes:
      - ./db-data:/var/lib/mysql 

  app-backend:
    image: belemon81/internship:pro-bookstore-backend
    # build: ./BookStore_BE
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/bookstore
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - app-network
    depends_on:
      - db

  app-frontend-ng:
    image: belemon81/internship:pro-bookstore-angular
    # build: ./BookStore_FE_Angular
    ports:
      - "4200:4200"
    networks:
      - app-network
    depends_on:
      - app-backend

  # app-frontend-react:
  #   image: belemon81/internship:pro-bookstore-react
  #   # build: ./BookStore_FE_React
  #   ports:
  #     - "4200:3000"
  #   networks:
  #     - app-network
  #   depends_on:
  #     - app-backend
